development:
      host: us-cdbr-iron-east-02.cleardb.net
      adapter: mysql
      database: heroku_e22b5f3eccfdfc2
      port: 3306
      username: b555a1e0eceea9
      password: e913395c

test: &test
      host: us-cdbr-iron-east-02.cleardb.net
      adapter: mysql
      database: heroku_e22b5f3eccfdfc2
      port: 3306
      username: b555a1e0eceea9
      password: e913395c

production:
      host: us-cdbr-iron-east-02.cleardb.net
      adapter: mysql
      database: heroku_e22b5f3eccfdfc2
      port: 3306
      username: b555a1e0eceea9
      password: e913395c
cucumber:
  <<: *test
